CREATE DATABASE STUDENTDB;

USE STUDENTDB;

CREATE TABLE MYTABLE (REG_NO INT PRIMARY KEY,
NAME VARCHAR(100),
AGE INT);

SELECT * FROM MYTABLE;

INSERT INTO MYTABLE (reg_no, name, age) 
VALUES 
    (1, 'PUSPAL', 23), 
    (2, 'AKASH', 19);
    
SELECT * FROM MYTABLE;